# Generated by Django 3.1.7 on 2021-06-18 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_auto_20210618_1726'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50, verbose_name='留言內容')),
                ('content_time', models.DateTimeField(auto_now_add=True)),
                ('num_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.ordersfiles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userprofile')),
            ],
            options={
                'db_table': 'messages',
            },
        ),
    ]
