# Generated by Django 3.1.7 on 2021-06-18 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_auto_20210618_1726'),
        ('order', '0001_initial'),
        ('product', '0004_auto_20210618_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='商品數量')),
                ('num_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.ordersfiles')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productprofile')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userprofile')),
            ],
            options={
                'db_table': 'orderlists',
            },
        ),
    ]
