# Generated by Django 3.1.7 on 2021-05-17 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('name', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='用戶名')),
                ('password', models.CharField(max_length=32, verbose_name='密碼')),
                ('birthday', models.CharField(max_length=10, null=True, verbose_name='生日')),
                ('phone', models.CharField(max_length=32, verbose_name='電話')),
                ('gender', models.CharField(max_length=10, null=True, verbose_name='性別')),
                ('email', models.CharField(max_length=50, verbose_name='信箱')),
                ('avatar', models.ImageField(upload_to='avatar/', verbose_name='頭像')),
                ('limit', models.IntegerField(default=1, verbose_name='權限')),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
