# Generated by Django 3.1.7 on 2021-06-18 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210612_1808'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='users',
        ),
    ]
