# Generated by Django 3.1.7 on 2021-06-12 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_auto_20210611_2123'),
        ('user', '0002_auto_20210612_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='商品數量')),
                ('price', models.IntegerField(verbose_name='商品金額')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userprofile')),
            ],
            options={
                'db_table': 'shoppinglist',
            },
        ),
    ]
