# Generated by Django 3.1.7 on 2021-06-18 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shoppinglist',
            table='shoppinglists',
        ),
    ]
