# Generated by Django 3.1.7 on 2021-12-18 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersFiles',
            fields=[
                ('num_list', models.IntegerField(primary_key=True, serialize=False, verbose_name='訂單編號')),
                ('num_time', models.CharField(max_length=20, verbose_name='訂單時間')),
                ('status', models.IntegerField(verbose_name='訂單狀態')),
                ('status_time', models.DateTimeField(auto_now=True)),
                ('gname', models.CharField(max_length=20, verbose_name='收貨人')),
                ('address', models.CharField(max_length=60, verbose_name='地址')),
                ('phone', models.CharField(max_length=11, verbose_name='電話')),
                ('payway', models.IntegerField(verbose_name='付款方式')),
                ('content', models.CharField(max_length=60, verbose_name='備註')),
                ('bonus', models.IntegerField(verbose_name='優惠')),
                ('shipping', models.IntegerField(verbose_name='運費')),
                ('money_total', models.IntegerField(verbose_name='總金額')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='user.userprofile')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='user.userprofile')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
