# Generated by Django 3.1.7 on 2021-06-18 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_auto_20210618_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='訂單編號')),
                ('num_time', models.CharField(max_length=30, verbose_name='訂單時間')),
                ('status', models.IntegerField(verbose_name='訂單狀態')),
                ('status_time', models.DateTimeField(auto_now=True)),
                ('gname', models.CharField(max_length=20, verbose_name='收貨人')),
                ('address', models.CharField(max_length=30, verbose_name='地址')),
                ('phone', models.CharField(max_length=20, verbose_name='電話')),
                ('payway', models.IntegerField(verbose_name='付款方式')),
                ('content', models.CharField(max_length=30, verbose_name='備註')),
                ('bonus', models.IntegerField(verbose_name='優惠')),
                ('shipping', models.IntegerField(verbose_name='運費')),
                ('money_total', models.IntegerField(verbose_name='總金額')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userprofile')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
