# Generated by Django 3.1.7 on 2021-06-19 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordersfiles',
            old_name='number',
            new_name='num_list',
        ),
    ]
