# Generated by Django 3.1.7 on 2021-06-20 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210618_1726'),
        ('order', '0002_auto_20210619_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersfiles',
            name='sales',
            field=models.ForeignKey(default='jimmy88', on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='user.userprofile'),
        ),
        migrations.AlterField(
            model_name='ordersfiles',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='user.userprofile'),
        ),
    ]
