# Generated by Django 3.1.7 on 2021-06-11 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprofile',
            name='pway',
            field=models.CharField(max_length=30, verbose_name='付款方式'),
        ),
    ]
