# Generated by Django 3.1.7 on 2021-06-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210611_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprofile',
            name='pway',
            field=models.IntegerField(verbose_name='付款方式'),
        ),
    ]
