# Generated by Django 3.1.7 on 2021-06-18 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210611_2123'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productprofile',
            table='products',
        ),
    ]
